// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhmlliieewayqtnafmfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobWxsaWllZXdheXF0bmFmbWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MzM2NzksImV4cCI6MjA2ODQwOTY3OX0.hxZhy_3RztYeGCj7qoPUuDK4ama4IGmt1gU5ts78MDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});